export enum CartAction {
  ADD_ITEM = 'ADD_ITEM',
  REMOVE_ONE = 'REMOVE_ONE',
  CLEAR_CART = 'CLEAR_CART',
  DELETE_ITEM = 'DELETE_ITEM',
  CALCULATE_CHANGE = 'CALCULATE_CHANGE',
  UPDATE_MULTIPLIER = 'UPDATE_MULTIPLIER',
}